-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "photoID" DROP NOT NULL,
ALTER COLUMN "userID" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Like" ALTER COLUMN "photoID" DROP NOT NULL,
ALTER COLUMN "userID" DROP NOT NULL;
